### ISSUE TITLE
./idba_to_gfa.py: line 1: payload:allShortcutsEnabled:false: command not found

### ISSUE THREAD

**Issue by atiaamin2019** [rrwick/IDBA-to-GFA#2]
Hi,

First of all, thanks for the script! When I tried to run, I got the following error
`./idba_to_gfa.py: line 1: payload:allShortcutsEnabled:false: command not found`
I am working on a cluster where I loaded idba-ud/1.1.3. Could you please let me know how I can solve this issue? Thanks in advance.

**Comment by rrwick** [comment]
Sorry, but this script is pretty old, so I'm afraid it's unsupported.

That being said, your error doesn't seem to have anything to do with the script itself. I think you might not have downloaded the script, but rather some sort of web page?
